# MongoDB Configuration
# https://docs.mongodb.com/manual/reference/configuration-options/

storage:
  dbPath: /data/db
  journal:
    enabled: true

net:
  port: 27017
  bindIp: 0.0.0.0

security:
  authorization: enabled

setParameter:
  authenticationMechanisms: SCRAM-SHA-256
