package com.orochiverse.platform.iam.operators;

import java.time.Instant;
import java.util.Objects;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import com.orochiverse.platform.common.tenant.TenantId;

/**
 * Grants an {@link com.orochiverse.platform.iam.users.UserKind#OPERATOR}
 * user the right to act inside one tenant. The operator's
 * {@link com.orochiverse.platform.iam.users.OperatorRole} (stored on the
 * user record) determines what they can do; this row simply enumerates
 * <em>which</em> tenants they can do it in.
 *
 * <p>The unique compound index on
 * {@code (operatorUserId, tenantId)} (created in Phase 1.4 Mongock) makes
 * duplicate grants impossible at the DB level.
 *
 * @param id              auto-generated; not semantically meaningful.
 * @param operatorUserId  references {@code users._id} of the operator.
 * @param tenantId        references {@code tenants._id} (and is the per-tenant DB key).
 * @param assignedBy      userId of the operator-admin who granted this assignment.
 * @param assignedAt      grant timestamp.
 */
@Document(collection = "operator_assignments")
public record OperatorAssignment(
        @Id String id,
        String operatorUserId,
        String tenantId,
        String assignedBy,
        Instant assignedAt) {

    public OperatorAssignment {
        Objects.requireNonNull(operatorUserId, "operatorUserId");
        Objects.requireNonNull(assignedBy, "assignedBy");
        Objects.requireNonNull(assignedAt, "assignedAt");
        TenantId.requireValid(tenantId);
    }

    /** Factory for new grants — id auto-generated by Mongo on save. */
    public static OperatorAssignment grant(String operatorUserId, String tenantId, String assignedBy) {
        return new OperatorAssignment(null, operatorUserId, tenantId, assignedBy, Instant.now());
    }
}
